"""Add category unique constraint and indexes

Revision ID: 8548fdccb0ec
Revises: f644cb5df0b2
Create Date: 2026-09-04 12:00:08.872976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8548fdccb0ec'
down_revision: Union[str, Sequence[str], None] = 'f644cb5df0b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_category_name_user', ['name', 'user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('uq_category_name_user', type_='unique')

    # ### end Alembic commands ###
